//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUcre.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public Estudiante()
        {
            this.DetalleAsignatura = new HashSet<DetalleAsignatura>();
        }
    
        public int IdEstudiante { get; set; }
        public string Nombre { get; set; }
        public string UserName { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<DetalleAsignatura> DetalleAsignatura { get; set; }
    }
}
