//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUcre.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRecurso
    {
        public TipoRecurso()
        {
            this.Recurso = new HashSet<Recurso>();
        }
    
        public int IdTipoRecurso { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Recurso> Recurso { get; set; }
    }
}
